apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chat-system

resources:
  - namespace.yaml
  - secrets.yaml
  - infrastructure.yaml
  - auth-service.yaml
  - chat-service.yaml
  - message-service.yaml
  - notification-service.yaml
  - api-gateway.yaml

commonLabels:
  app.kubernetes.io/part-of: chat-system
  app.kubernetes.io/managed-by: kustomize
